version: '3.8'
services:
  my-aspnet-api:
    build: ./back-end
    ports:
      - '5000:80'
    depends_on:
      - db
  my-react-app:
    build: ./front-end
    ports:
      - '3000:80'
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ****
      MYSQL_DATABASE: Todo
      MYSQL_USER: ****
      MYSQL_PASSWORD: ****
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: {}
